### ISSUE TITLE
Wrong path when not using a virtualenv

### ISSUE THREAD

**Issue by birdy-** [davedoesdev/python-jwt#10]
If I install this package without a virtualenv, my package is in /usr/local/local/lib/python2.7/dist-packages (there is local twice in the path).

It happened with jwt==0.3.2, python-jwt==0.3.3 and python-jwt==1.0.0

**Comment by davedoesdev** [comment]
Confirmed (Ubuntu 14.10).

**Comment by davedoesdev** [comment]
Bento has some funky stuff which sets the prefix to `/usr/local` on Debian/Ubuntu. I guess that is now not necessary.

**Comment by davedoesdev** [comment]
TBH I think it I should move away from Bento since it seems to be abandonware. Pity.
What's the current state-of-the-art in Python packaging? The whole thing historically has been a right mess.

**Comment by davedoesdev** [comment]
I guess I should follow this: https://packaging.python.org/en/latest/distributing.html
@birdy- this may take a few days to get round to.

**Comment by birdy-** [comment]
Ok great ! I see with some dev here if they have input on packaging to share via comment or PR.

Do you think it would be possible to backport this patch easily to an old release of jwt ? We are using jwt===0.3.3 here :(

If it's not easy, maybe it's time for us to move forward :)

**Comment by davedoesdev** [comment]
@birdy- Are you using the `jwt` package or the `python_jwt` package?

**Comment by davedoesdev** [comment]
OK, python-jwt is now using setuptools. RIP Bento.
@birdy- would you mind trying version 1.0.2 please? Thanks.

**Comment by birdy-** [comment]
Nice, and thanks matbu :)
We use jwt 0.3.3 with python_jwt pypi package. I can try to upgrade our dependency to 1.0.2, but I think it'll fail. I'll try it on friday.

**Comment by davedoesdev** [comment]
Yes, the API changed but it shouldn't be too difficult to adapt (need to pass in allowed algorithms).

**Comment by davedoesdev** [comment]
Hi @birdy- @matbu Thanks for your help on the switch.
Did you manage to upgrade OK?

**Comment by birdy-** [comment]
Sadly I didn't spend time on this issue since friday. Can you publish a new jwt version with the @matbu patch on pip repository ? I'll try to use it as soon as I can.
FYI, we tried to deploy our app on docker, that's why we decided to not use virtualenv. By the way, it's not critical for us, we are just experimenting yet.

**Comment by davedoesdev** [comment]
No worries. Version 1.0.2 is on PyPI. If you could give it a try that would be great.

**Comment by davedoesdev** [comment]
@birdy- @matbu version 1.03 is on PyPI, just updated links in the docs.
Do you still have a issue or can I close this issue out?

**Comment by birdy-** [comment]
Everything seems fine ! Thank you ! :)
