### ISSUE TITLE
Clashes with pyjwt

### ISSUE THREAD

**Issue by aericson** [davedoesdev/python-jwt#14]
I'm using `python-social-auth` on the same virtualenv and one of it requirements is https://github.com/jpadilla/pyjwt.

This causes the `import jwt` to clash. How can I solve this?

**Comment by davedoesdev** [comment]
Wow - installing the second one overwrites the files of the first.
Does Python have a mode similar to Node - i.e. packages install their dependencies under a subdirectory?

I've always found Python packaging rather cumbersome.

**Comment by aericson** [comment]
I'm afraid it doesn't.

I've managed to do what I want using the other pyjwt. I think you would need to rename your module. Feel free to close this issue if you think it's not worth the trouble.

**Comment by davedoesdev** [comment]
Version 2.0.1 onwards changes the namespace to `python_jwt` to avoid the clash.
@aericson thanks for the heads up. If you get time could you just install the latest version and double check the namespace has changed and doesn't overwrite PyJWT please?

**Comment by aericson** [comment]
Looks good now 👍
