### ISSUE TITLE
Is this a naming error?

### ISSUE THREAD

**Issue by Gu-f** [davedoesdev/python-jwt#25]
```python
def generate_jwt(claims, priv_key=None,
                 algorithm='PS512', lifetime=None, expires=None,
                 not_before=None,
                 jti_size=16, other_headers=None):
    pass
```

```python
def verify_jwt(jwt,
               pub_key=None,
               allowed_algs=None,
               iat_skew=timedelta(),
               checks_optional=False,
               ignore_not_implemented=False):
    pass
```
In parameter.  
Should `priv_key` and `pub_key` be the same, should they both be `priv_key`?  

Here is your example:  
```python
...
---> key = jwk.JWK.generate(kty='RSA', size=2048)
...
---> token = jwt.generate_jwt(payload, key, 'PS256', datetime.timedelta(minutes=5))
---> header, claims = jwt.verify_jwt(token, key, ['PS256'])
...
```
This `key` is the same variable.

**Comment by davedoesdev** [comment]
Hi @Gu-f thanks for your question. In this case, `key` can be used for both since [`jwk.JWK.generate`](https://jwcrypto.readthedocs.io/en/latest/jwk.html#jwcrypto.jwk.JWK) generates a key that has both a public and private part.

**Comment by Gu-f** [comment]
> Hi @Gu-f thanks for your question. In this case, `key` can be used for both since [`jwk.JWK.generate`](https://jwcrypto.readthedocs.io/en/latest/jwk.html#jwcrypto.jwk.JWK) generates a key that has both a public and private part.

Thanks
