### ISSUE TITLE
In two node, data is resolved normaly?

### ISSUE THREAD

**Issue by rfyiamcool** [davedoesdev/python-jwt#9]
In two node, data is resolved normaly?

**Comment by davedoesdev** [comment]
Hi @rfyiamcool. Thanks for your question - could you elaborate please?

**Comment by davedoesdev** [comment]
@rfyiamcool The data is parsed from the JSON payload.
What do you mean by two nodes?

**Comment by davedoesdev** [comment]
@rfyiamcool Please could you clarify, otherwise I'll close this.
